# Generated by Django 5.0.7 on 2026-04-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific JSON config (API key, URL, etc.)')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'external_catalog_sources',
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('method', models.CharField(choices=[('straight_line', 'Straight Line'), ('diminishing_balance', 'Diminishing Balance'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=30)),
                ('default_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='Annual depreciation rate (e.g. 0.10 = 10%)', max_digits=5)),
                ('salvage_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='Salvage value as fraction of purchase price', max_digits=5)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=10)),
                ('units_lifetime', models.PositiveIntegerField(blank=True, help_text='Total expected units (for UoP method)', null=True)),
            ],
            options={
                'verbose_name': 'Depreciation Policy',
                'verbose_name_plural': 'Depreciation Policies',
                'db_table': 'depreciation_policies',
                'unique_together': {('category', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ItemCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=30)),
                ('confidence_default', models.FloatField(default=1.0, help_text='Default confidence score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Catalog Entry',
                'verbose_name_plural': 'Item Catalog',
                'db_table': 'item_catalog',
                'unique_together': {('title', 'category')},
            },
        ),
    ]
