# Generated by Django 5.0.7 on 2026-04-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('projects', '0019_projectdocument_visible_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('md_approved', 'MD/GM Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='project_reports/%Y/%m/')),
                ('accessor_comments', models.TextField(blank=True)),
                ('senior_valuer_comments', models.TextField(blank=True)),
                ('md_gm_comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='projects.project')),
            ],
            options={
                'db_table': 'project_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('depreciation_method', models.CharField(blank=True, max_length=30)),
                ('applied_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('units_used', models.IntegerField(blank=True, null=True)),
                ('units_lifetime', models.IntegerField(blank=True, null=True)),
                ('computed_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('override_reason', models.TextField(blank=True, help_text='Reason when depreciation is manually overridden')),
                ('is_merged_duplicate', models.BooleanField(default=False)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_items', to=settings.AUTH_USER_MODEL)),
                ('catalog_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_items', to='catalog.itemcatalog')),
                ('merged_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_items', to='reports.valuationitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.projectreport')),
            ],
            options={
                'db_table': 'valuation_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='item_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.valuationitem')),
            ],
            options={
                'db_table': 'valuation_item_photos',
                'ordering': ['ordering', '-uploaded_at'],
            },
        ),
    ]
