# Generated by Django 5.0 on 2026-02-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_commissionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Admin approval status for direct projects (created without a submission)', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by admin (if rejected)', null=True),
        ),
    ]
