# Generated by Django 5.0 on 2026-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Admin approval status for direct projects (created without a submission)', max_length=20),
        ),
    ]
