# Generated by Django 5.0.7 on 2026-04-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectpayment_gateway_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this document (empty = all project assignees + coordinator)', related_name='visible_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The assigned user this document is intended for (legacy; use visible_to for ACL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.project')),
            ],
            options={
                'db_table': 'project_visits',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
