from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView,
    LoginView,
    UserProfileView,
    ChangePasswordView,
    PasswordResetRequestView,
    PasswordResetVerifyOTPView,
    PasswordResetConfirmView,
    AssignRoleView,
    AllUsersView,
    DeleteUserView,
    RoleListView,
    MyRoleView,
    GeneratePaymentSlipsView,
    UploadPaymentSlipsView,
    MyPaymentSlipsView,
    AllPaymentSlipsView,
    PaymentSlipDetailView,
    UploadOvertimeHoursView,
    UploadAllOvertimeHoursView,
    SyncOvertimeFromAttendanceView,
    EmployeeRegistrationView,
    CreateLeaveRequestView,
    AllLeaveRequestsView,
    MyLeaveRequestsView,
    MyLeaveStatisticsView,
    MonthlyLeaveSummaryView,
    UpdateLeaveRequestView,
    CreateEmployeeRemovalRequestView,
    AllRemovalRequestsView,
    ApproveRemovalRequestView,
    RejectRemovalRequestView,
    AllClientSubmissionsView,
    ClientSubmissionDetailView,
    AssignCoordinatorView,
    AvailableCoordinatorsView,
    ApproveClientSubmissionView,
    AllEmployeeSubmissionsView,
    EmployeeSubmissionDetailView,
    HireEmployeeSubmissionView,
    RoleSalariesView,
    AcceptAssignmentView,
    RejectAssignmentView,
    AdminDashboardStatsView,
    AdminKPIView,
    InvitationListView,
    PublicCheckEmailView,
    CancelLeaveRequestView,
    LeaveBalanceView,
    LeavePolicyListView,
    LeavePolicyDetailView,
    UserProfileMeView,
    UserAvatarUploadView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/verify-otp/', PasswordResetVerifyOTPView.as_view(), name='password-reset-verify-otp'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('my-role/', MyRoleView.as_view(), name='my-role'),
    path('roles/', RoleListView.as_view(), name='roles'),
    path('assign-role/', AssignRoleView.as_view(), name='assign-role'),
    path('users/', AllUsersView.as_view(), name='all-users'),
    path('users/<int:user_id>/delete/', DeleteUserView.as_view(), name='delete-user'),
    path('payment-slips/generate/', GeneratePaymentSlipsView.as_view(), name='generate-payment-slips'),
    path('payment-slips/upload/', UploadPaymentSlipsView.as_view(), name='upload-payment-slips'),
    path('payment-slips/my/', MyPaymentSlipsView.as_view(), name='my-payment-slips'),
    path('payment-slips/', AllPaymentSlipsView.as_view(), name='all-payment-slips'),
    path('payment-slips/<int:pk>/', PaymentSlipDetailView.as_view(), name='payment-slip-detail'),
    path('payment-slips/<int:slip_id>/upload-overtime/', UploadOvertimeHoursView.as_view(), name='upload-overtime-hours'),
    path('payment-slips/upload-all-overtime/', UploadAllOvertimeHoursView.as_view(), name='upload-all-overtime-hours'),
    path('payment-slips/sync-overtime/', SyncOvertimeFromAttendanceView.as_view(), name='sync-overtime-from-attendance'),
    path('leave-requests/create/', CreateLeaveRequestView.as_view(), name='create-leave-request'),
    path('leave-requests/my/', MyLeaveRequestsView.as_view(), name='my-leave-requests'),
    path('leave-requests/statistics/', MyLeaveStatisticsView.as_view(), name='my-leave-statistics'),
    path('leave-requests/summary/monthly/', MonthlyLeaveSummaryView.as_view(), name='monthly-leave-summary'),
    path('leave-requests/', AllLeaveRequestsView.as_view(), name='all-leave-requests'),
    path('leave-requests/<int:pk>/update/', UpdateLeaveRequestView.as_view(), name='update-leave-request'),
    path('removal-requests/create/', CreateEmployeeRemovalRequestView.as_view(), name='create-removal-request'),
    path('removal-requests/', AllRemovalRequestsView.as_view(), name='all-removal-requests'),
    path('removal-requests/<int:request_id>/approve/', ApproveRemovalRequestView.as_view(), name='approve-removal-request'),
    path('removal-requests/<int:request_id>/reject/', RejectRemovalRequestView.as_view(), name='reject-removal-request'),
    # Client submissions management
    path('client-submissions/', AllClientSubmissionsView.as_view(), name='all-client-submissions'),
    path('client-submissions/<int:pk>/', ClientSubmissionDetailView.as_view(), name='client-submission-detail'),
    path('client-submissions/<int:pk>/assign-coordinator/', AssignCoordinatorView.as_view(), name='assign-coordinator'),
    path('client-submissions/<int:pk>/approve/', ApproveClientSubmissionView.as_view(), name='approve-client-submission'),
    path('client-submissions/<int:pk>/accept/', AcceptAssignmentView.as_view(), name='accept-assignment'),
    path('client-submissions/<int:pk>/reject/', RejectAssignmentView.as_view(), name='reject-assignment'),
    path('coordinators/', AvailableCoordinatorsView.as_view(), name='available-coordinators'),
    # Employee submissions management
    path('employee-submissions/', AllEmployeeSubmissionsView.as_view(), name='all-employee-submissions'),
    path('employee-submissions/<int:pk>/', EmployeeSubmissionDetailView.as_view(), name='employee-submission-detail'),
    path('employee-submissions/<int:pk>/hire/', HireEmployeeSubmissionView.as_view(), name='hire-employee-submission'),
    path('role-salaries/', RoleSalariesView.as_view(), name='role-salaries'),
    path('admin-dashboard-stats/', AdminDashboardStatsView.as_view(), name='admin-dashboard-stats'),
    path('admin-kpis/', AdminKPIView.as_view(), name='admin-kpis'),
    # Feature #6 – invitations
    path('invitations/', InvitationListView.as_view(), name='invitations-list'),
    # Feature #7 – public email check (also available under projects/public/check-email)
    path('public/check-email/', PublicCheckEmailView.as_view(), name='public-check-email'),
    # Feature #15 – leave balance + policy + cancel
    path('leave-requests/<int:pk>/cancel/', CancelLeaveRequestView.as_view(), name='cancel-leave-request'),
    path('leave-balance/', LeaveBalanceView.as_view(), name='leave-balance'),
    path('leave-policies/', LeavePolicyListView.as_view(), name='leave-policies'),
    path('leave-policies/<int:pk>/', LeavePolicyDetailView.as_view(), name='leave-policy-detail'),
    # Feature #16 – user profile
    path('profile/me/', UserProfileMeView.as_view(), name='profile-me'),
    path('profile/me/avatar/', UserAvatarUploadView.as_view(), name='profile-avatar'),
]

