"""
Django settings for auditra_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from the backend .env file explicitly so the
# payment gateway settings are available regardless of the working directory.
config = Config(RepositoryEnv(str(BASE_DIR / '.env')))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-r)araqzfhx*5#jg&l4%5@gsq+@hw$c=8$)6#m8qlj_a+tizn6j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Get allowed hosts from environment variable (comma-separated) or use default
ALLOWED_HOSTS_ENV = config('ALLOWED_HOSTS', default='*')
ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(',') if ALLOWED_HOSTS_ENV else ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'django_celery_beat',
    # Project apps
    'authentication',
    'attendance',
    'projects',
    'valuations',
    'system_logs',
    # New apps
    'notifications',
    'standups',
    'catalog',
    'reports',
    'reports_v2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'system_logs.middleware.SystemLogMiddleware',
]

ROOT_URLCONF = 'auditra_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auditra_backend.wsgi.application'
ASGI_APPLICATION = 'auditra_backend.asgi.application'

# Django Channels channel layer
# Uses InMemoryChannelLayer for local development (avoids needing Redis 5+).
# Switch to RedisChannelLayer for production (requires Redis >= 5.0).
_USE_REDIS_CHANNEL_LAYER = config('USE_REDIS_CHANNEL_LAYER', default='False') == 'True'
if _USE_REDIS_CHANNEL_LAYER:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [config('REDIS_URL', default='redis://localhost:6379')],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Celery settings
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Periodic tasks (Feature #2 — visit reminders runs daily at 08:00 local time).
from celery.schedules import crontab  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'send-visit-reminders-daily': {
        'task': 'projects.send_visit_reminders',
        'schedule': crontab(hour=8, minute=0),
    },
    'compute-leave-deductions-monthly': {
        'task': 'authentication.compute_leave_deductions',
        'schedule': crontab(hour=1, minute=0, day_of_month=28),
    },
}

# FCM settings
FCM_CREDENTIALS_PATH = config('FCM_CREDENTIALS_PATH', default='')


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='auditra_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailOrUsernameBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Colombo'  # Sri Lankan timezone (UTC+5:30)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)  # Set to False in production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://152.42.240.220",
    "https://152.42.240.220",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.0.2.2:3000",
] if not DEBUG else [
    "http://152.42.240.220",
    "https://152.42.240.220",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.0.2.2:3000",
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Email Configuration
# Using SendGrid API (works even when SMTP ports are blocked)
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='auditra.auditing.erp@gmail.com')

# SendGrid settings
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Set to True for testing without sending real emails

# Email timeout settings (for SendGrid API calls)
EMAIL_TIMEOUT = 30  # seconds

# Frontend URL (used for login links in emails)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# PayHere payment gateway settings
PAYHERE_MERCHANT_ID = config('PAYHERE_MERCHANT_ID', default='1235300')
PAYHERE_MERCHANT_SECRET = config(
    'PAYHERE_MERCHANT_SECRET',
    default='NDE1NDQ4ODY5NzE4NDEzMzA1MzQyMjc0NzIzNjIwMTIzMDM3NDg0Mw=='
)
PAYHERE_CURRENCY = config('PAYHERE_CURRENCY', default='LKR')
PAYHERE_CHECKOUT_URL = config('PAYHERE_CHECKOUT_URL', default='https://sandbox.payhere.lk/pay/checkout')
PAYHERE_RETURN_URL = config('PAYHERE_RETURN_URL', default=f'{FRONTEND_URL}/dashboard/client-payments')
PAYHERE_CANCEL_URL = config('PAYHERE_CANCEL_URL', default=f'{FRONTEND_URL}/dashboard/client-payments')
PAYHERE_NOTIFY_URL = config('PAYHERE_NOTIFY_URL', default='http://localhost:8000/api/projects/payhere/notify/')
PAYHERE_DUMMY_MODE = config('PAYHERE_DUMMY_MODE', default=True, cast=bool)