# Generated by Django 5.0.7 on 2026-05-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0020_add_urgent_priority'),
        ('valuations', '0009_alter_valuationphoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depreciation_method', models.CharField(blank=True, choices=[('straight_line', 'Straight Line'), ('diminishing_balance', 'Diminishing Balance'), ('units_of_production', 'Units of Production')], default='', max_length=30)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_items', to=settings.AUTH_USER_MODEL)),
                ('merged_from_valuation', models.ForeignKey(blank=True, help_text='Set when this row was auto-migrated from an existing Valuation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_report_items', to='valuations.valuation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'Report Item',
                'verbose_name_plural': 'Report Items',
                'db_table': 'report_items',
                'ordering': ['project', 'category', 'name'],
            },
        ),
    ]
