# Generated by Django 5.0.7 on 2026-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0008_notification_valuationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuationphoto',
            options={'ordering': ['ordering', '-uploaded_at'], 'verbose_name': 'Valuation Photo', 'verbose_name_plural': 'Valuation Photos'},
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='device_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valuationphoto',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
